version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email_automation_backend
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: email_automation_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend